apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dasmlab-home-gitrepo
  namespace: dasmlab-livecicd
spec:
  interval: 30s
  url: "https://github.com/lmcdasm/dasmlab-live-cicd.git"
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dasmlab-home-kustomization
  namespace: dasmlab-livecicd
spec:
  interval: 1m0s
  path: "./clusters/dasmlab-prod-1/dasmlab_home/live"
  prune: true
  sourceRef:
    kind: GitRepository
    name: dasmlab-home-gitrepo
  targetNamespace: dasmlab-home-system

